// TEMPORARY Stage 0b audit script (docs/development/audits/stage-0.md). Builds
// platform-reprobe.jsonl: minimal queries whose verdict needs a real 1C
// platform. Nothing here is a confirmed gap until reprobed.
// Each row carries `reprobeOracleRecord` in the shape src/cli/reprobeOracle.ts
// reads ({файл, исходныйТекстЗапроса, текстВалидатора}); write each record to its
// own <id>.json in the configured errors directory and run
// `npm run oracle:reprobe -- --all`. Do NOT use harvestOracle for these: it
// deletes rejected inputs and records no invalid verdict.
// Metadata names come from test/fixtures/corpus/metadata/cf (the same
// configuration the golden corpus was recorded against); rows marked
// `metadataCheck: true` reference names from oracle fixtures of unknown
// provenance and may fail on metadata rather than syntax.
// Run: npx tsx docs/development/audits/stage-0/probes/buildReprobeQueue.ts $PWD
import * as fs from 'fs';
import * as path from 'path';
const ROOT = process.argv[2];
const probes = new Map<string, any>(JSON.parse(fs.readFileSync(path.join(ROOT, 'docs/development/audits/stage-0/probes/construct-probes.json'), 'utf8')).map((p: any) => [p.id, p]));
const fixture = (f: string) => JSON.parse(fs.readFileSync(path.join(ROOT, 'test/fixtures/oracle', f), 'utf8'));

interface Row { id: string; priority: 'high' | 'medium' | 'low'; check: string; question: string; ifValid: string; ifInvalid: string; sourceCaseIds: string[]; text: string; metadataCheck?: boolean }
const P = (id: string) => probes.get(id).text as string;
const rows: Row[] = [
  { id: 'RP01', priority: 'high', check: 'acceptance + canonical text', question: 'Is a full-name-qualified boolean field valid as a whole WHERE condition when the source has no alias?', ifValid: 'P0-Critical: we emit `Валюты.Справочник.Валюты.ПометкаУдаления` and Apply would write it (apply-gate.jsonl)', ifInvalid: 'P3: invalid input mangled', sourceCaseIds: ['probe:R01'], text: P('R01') },
  { id: 'RP02', priority: 'high', check: 'acceptance + canonical text', question: 'Same inside an IN-subquery without alias', ifValid: 'P0-Critical (first pass doubles the qualifier; Apply would write it)', ifInvalid: 'P3', sourceCaseIds: ['probe:R02', 'probe:R03'], text: P('R02') },
  { id: 'RP03', priority: 'high', check: 'acceptance', question: 'Is the oracle fixture 0163 expected (canonical) text itself valid? Our second parse→generate pass doubles the qualifier', ifValid: 'P0-Critical: reopening already-canonical text corrupts it and Apply would write it', ifInvalid: 'fixture 0163 expected is wrong (fixture provenance issue)', sourceCaseIds: ['oracle:0163-where-subquery-bare-source-qualifies-fields.json', 'oracle:0164-negated-where-hierarchy-subquery-qualifies.json', 'probe:R05'], text: fixture('0163-where-subquery-bare-source-qualifies-fields.json').expected, metadataCheck: true },
  { id: 'RP04', priority: 'high', check: 'acceptance', question: 'Does `Обороты` accept a 5th positional argument?', ifValid: 'P0-Critical: the 5th argument is dropped silently, not marked unsafe, Apply writes', ifInvalid: 'P3: invalid input silently normalized (still worth an unsafe marker)', sourceCaseIds: ['probe:V05', 'probe:V07'], text: P('V05') },
  { id: 'RP05', priority: 'high', check: 'acceptance', question: 'Does `ОстаткиИОбороты` accept a 6th positional argument?', ifValid: 'P0-Critical (same as RP04)', ifInvalid: 'P3', sourceCaseIds: ['probe:V06'], text: P('V06') },
  { id: 'RP06', priority: 'high', check: 'acceptance + canonical text', question: 'English keywords with Russian metadata type names', ifValid: 'P0: every English-syntax query is rejected by our parser (tree-sitter accepts)', ifInvalid: 'competitor over-acceptance', sourceCaseIds: ['probe:X02', 'ext-antlr:select06.sdbl'], text: P('X02') },
  { id: 'RP07', priority: 'high', check: 'acceptance + canonical text', question: 'Fully English query (Catalog.<name>)', ifValid: 'P0 (same as RP06)', ifInvalid: 'competitor over-acceptance', sourceCaseIds: ['probe:X01'], text: P('X01') },
  { id: 'RP08', priority: 'medium', check: 'acceptance + canonical text', question: '`УПОРЯДОЧИТЬ ПО <field> ИЕРАРХИЯ УБЫВ`', ifValid: 'P0: we reject it (tree-sitter accepts)', ifInvalid: 'competitor over-acceptance', sourceCaseIds: ['probe:O04', 'ext-ts:select.sdbl#Select top-level ordering'], text: P('O04') },
  { id: 'RP09', priority: 'medium', check: 'acceptance', question: 'Two ИТОГИ clauses in one query', ifValid: 'P0: we reject it', ifInvalid: 'H: competitor over-acceptance (tree-sitter accepts)', sourceCaseIds: ['probe:T04', 'ext-ts:select.sdbl#Select auto-ordering and totals', 'ext-ts:select.sdbl#Select totals periods'], text: P('T04') },
  { id: 'RP10', priority: 'medium', check: 'acceptance + canonical text', question: 'Field alias without КАК whose name is also a keyword (`Ссылка`)', ifValid: 'P0 (narrow): we reject it; aliases without КАК otherwise work', ifInvalid: 'competitor over-acceptance', sourceCaseIds: ['ext-ts:select.sdbl#Allowed fields parameters and boolean conditions'], text: 'ВЫБРАТЬ\n\tВал.Ссылка Ссылка\nИЗ\n\tСправочник.Валюты Вал' },
  { id: 'RP11', priority: 'medium', check: 'acceptance', question: 'Source alias equal to the keyword В', ifValid: 'P0: `НЕ В.Поле` is mangled to `НЕ В. В .Поле` (Apply blocked by malformedCustom, so visible, not silent)', ifInvalid: 'P3', sourceCaseIds: ['probe:K01', 'probe:K02', 'probe:K03'], text: P('K01') },
  { id: 'RP12', priority: 'medium', check: 'acceptance', question: 'Source alias equal to the keyword И', ifValid: 'P0 (same class as RP11)', ifInvalid: 'P3', sourceCaseIds: ['probe:K04'], text: P('K04') },
  { id: 'RP13', priority: 'medium', check: 'acceptance', question: 'Parameter named like a keyword (`&И`)', ifValid: 'P0: generated as `& И`, final check rejects it (Apply blocked)', ifInvalid: 'P3', sourceCaseIds: ['probe:K05'], text: P('K05') },
  { id: 'RP14', priority: 'medium', check: 'acceptance + canonical text', question: '`ПУСТАЯТАБЛИЦА.(Код, Наименование)` in the select list', ifValid: 'P0: we qualify the column names with the source alias (Apply blocked by malformedCustom)', ifInvalid: 'P3', sourceCaseIds: ['probe:P03'], text: P('P03') },
  { id: 'RP15', priority: 'low', check: 'acceptance', question: 'Scalar subquery in the select list', ifValid: 'P0: our output drops its parentheses (final check rejects it)', ifInvalid: 'P3: over-acceptance', sourceCaseIds: ['probe:E30'], text: P('E30') },
  { id: 'RP16', priority: 'low', check: 'acceptance + canonical text', question: 'Parenthesized nested join source', ifValid: 'P0: both parsers reject it', ifInvalid: 'none', sourceCaseIds: ['probe:J07'], text: P('J07') },
  { id: 'RP17', priority: 'medium', check: 'acceptance + canonical text', question: '`ИНДЕКСИРОВАТЬ ПО` without `ПОМЕСТИТЬ`', ifValid: 'P0-Critical candidate: our generator drops the INDEX BY clause silently', ifInvalid: 'P3', sourceCaseIds: ['ext-ts:select.sdbl#Select index clause after where'], text: 'ВЫБРАТЬ\n\tВал.Код КАК Код\nИЗ\n\tСправочник.Валюты КАК Вал\n\nИНДЕКСИРОВАТЬ ПО\n\tВал.Код' },
  { id: 'RP18', priority: 'low', check: 'canonical text', question: 'Does the platform itself drop the parentheses in `НЕ (a + 2 * b > 10)`? (equivalence of our output)', ifValid: 'if canonical keeps them, our output needs an equivalence check', ifInvalid: 'n/a', sourceCaseIds: ['ext-ts:select.sdbl#Select arithmetic precedence and unary signs'], text: 'ВЫБРАТЬ\n\tВал.Код КАК Код\nИЗ\n\tСправочник.Валюты КАК Вал\nГДЕ\n\tНЕ (Вал.Наценка + 2 * Вал.Наценка > 10)' },
  { id: 'RP19', priority: 'medium', check: 'canonical text', question: 'Fixture 0150 claims the constructor drops a bare parameter from GROUP BY — confirm (fixture provenance unknown)', ifValid: 'fixture confirmed', ifInvalid: 'our output removes a GROUP BY element: P0-Critical candidate', sourceCaseIds: ['oracle:0150-group-by-drops-bare-param.json'], text: fixture('0150-group-by-drops-bare-param.json').input, metadataCheck: true },
  { id: 'RP20', priority: 'medium', check: 'canonical text', question: 'Fixture 0078 claims ORDER BY ИЕРАРХИЯ is dropped for a non-reference field — confirm', ifValid: 'fixture confirmed', ifInvalid: 'semantic change candidate', sourceCaseIds: ['oracle:0078-order-hierarchy-dropped-nonref.json', 'oracle:0121-order-hierarchy-dropped-param-table-alias.json'], text: fixture('0078-order-hierarchy-dropped-nonref.json').input, metadataCheck: true },
  { id: 'RP21', priority: 'medium', check: 'canonical text', question: 'Fixture 0127 claims a bare ИТОГИ name is rewritten to the column alias `Валюта2` — confirm', ifValid: 'fixture confirmed', ifInvalid: 'semantic change candidate', sourceCaseIds: ['oracle:0127-totals-bare-name-rewritten-to-column-alias.json'], text: fixture('0127-totals-bare-name-rewritten-to-column-alias.json').input, metadataCheck: true },
  { id: 'RP22', priority: 'medium', check: 'acceptance', question: 'Does validate_query accept a `#Имя` template marker as a source? (24 golden entries contain `#` markers and are recorded valid)', ifValid: 'the MCP validator substitutes or tolerates templates: golden `valid` is not a pure platform verdict for those entries', ifInvalid: 'those golden entries were recorded differently: investigate golden provenance', sourceCaseIds: ['probe:X05'], text: P('X05') },
  { id: 'RP23', priority: 'low', check: 'acceptance + canonical text', question: 'Quoted date literal `\'20240101000000\'` in a condition', ifValid: 'confirms current acceptance', ifInvalid: 'P3: over-acceptance by us and tree-sitter', sourceCaseIds: ['probe:E24'], text: P('E24') },
  { id: 'RP24', priority: 'low', check: 'acceptance + canonical text', question: '`Последовательность.*.Границы` with 3 arguments — settle the real layout (documented limitation)', ifValid: 'layout can be modeled; currently blocked as unsafe', ifInvalid: 'limitation can be narrowed to arity 2', sourceCaseIds: ['probe:V10'], text: P('V10') },
  { id: 'RP25', priority: 'low', check: 'acceptance + canonical text', question: '`Задача.*.ЗадачиПоИсполнителю(…, …)` through the generic positional fallback', ifValid: 'confirms generic layout is lossless for this form', ifInvalid: 'n/a', sourceCaseIds: ['probe:Z01'], text: P('Z01') },
];
const out = rows.map(r => JSON.stringify({ ...r, reprobeOracleRecord: { файл: `stage0-${r.id}.txt`, исходныйТекстЗапроса: r.text, текстВалидатора: '' } }));
fs.writeFileSync(path.join(ROOT, 'docs/development/audits/stage-0/platform-reprobe.jsonl'), out.join('\n') + '\n');
console.error(`wrote ${rows.length} reprobe rows`);
